# Generated by Django 5.2.1 on 2025-09-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('display_name', models.CharField(max_length=250)),
                ('profile_image_url', models.ImageField(blank=True, upload_to='')),
                ('bio_text', models.TextField()),
                ('join_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
