# Generated by Django 5.2.1 on 2025-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectuser_first_name_projectuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='last_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
