# Generated by Django 5.2.1 on 2025-06-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projectuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
