# Generated by Django 5.2.1 on 2025-06-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_enrollment_student_alter_report_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='first_name',
            field=models.CharField(default='unknown', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='last_name',
            field=models.CharField(default='unknown', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='student_id',
            field=models.CharField(blank=True, default='unknown', max_length=10),
            preserve_default=False,
        ),
    ]
