# Generated by Django 5.2.1 on 2025-06-21 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_projectuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
