# Generated by Django 5.2.1 on 2025-06-22 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
