# Generated by Django 5.2.1 on 2025-06-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_image_statusimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
